name: PR Artifact Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

jobs:
  upload-artifact-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd packages/one
          npm install
          npm run build
          npm run analyze
          cd ../two
          npm install
          npm run build
          npm run analyze

      - name: Get latest commit hash from main
        id: latest_commit
        run: |
          git fetch origin main
          latest_commit=$(git rev-parse origin/main)
          echo "latest_commit=$latest_commit" >> $GITHUB_OUTPUT

      - name: Check if previous artifact exists
        env:
          LATEST_COMMIT: ${{ steps.latest_commit.outputs.latest_commit }}
        id: artifact_check
        run: |
          ARTIFACT_EXISTS=$(curl -s -H "Authorization: Bearer ${{ github.token }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=reports-$LATEST_COMMIT" | jq '.total_count' | awk '{print $1}')
          if [[ $ARTIFACT_EXISTS -gt 0 ]]; then
            echo "artifact_exists=true" >> $GITHUB_OUTPUT
          else
            echo "artifact_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Get artifact URL
        id: get_artifact_url
        env:
          LATEST_COMMIT: ${{ steps.latest_commit.outputs.latest_commit }}
        run: |
          ARTIFACT_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=reports-${LATEST_COMMIT}" | \
            jq -r '.artifacts[0].archive_download_url')
          echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_OUTPUT

      - name: Download artifact
        if: steps.get_artifact_url.outputs.artifact_url != 'null'
        env:
          ARTIFACT_URL: ${{ steps.get_artifact_url.outputs.artifact_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L -H "Authorization: Bearer $GITHUB_TOKEN" \
            "$ARTIFACT_URL" \
            -o artifact.zip
          unzip artifact.zip -d old
          cd old
          unzip reports.zip

      - name: Compare report to main
        id: diff
        if: steps.get_artifact_url.outputs.artifact_url != 'null'
        run: |
          DIFF_OUTPUT=$(node .github/workflows/compareReports.js)
          echo "diff_output<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Zip all report.json files
        run: |
          zip -r reports.zip packages/*/report.json
        shell: bash

      - name: Upload New Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.sha }}
          path: reports.zip

      - name: Comment on PR with Artifact URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          script: |
            const artifactUrl = '${{ steps.upload-artifact.outputs.artifact-url }}';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Hello World artifact is available here: ${artifactUrl}`
            });

      - name: Comment on PR with Diff Output
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        env:
          DIFF_OUTPUT: ${{ steps.diff.outputs.diff_output }}
        with:
          script: |
            const diffOutput = process.env.DIFF_OUTPUT;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${diffOutput}`
            });
