name: PR Artifact Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

jobs:
  upload-artifact-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd packages/one
          npm install
          npm run build
          npm run analyze

      - name: Get latest commit hash from main
        id: latest_commit
        run: |
          git fetch origin main
          LATEST_COMMIT=$(git rev-parse origin/main)
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV

      - name: Check if previous artifact exists
        id: artifact_check
        run: |
          ARTIFACT_EXISTS=$(curl -s -H "Authorization: Bearer ${{ github.token }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=reports-${{ env.LATEST_COMMIT }}" | jq '.total_count' | awk '{print $1}')
          if [[ $ARTIFACT_EXISTS -gt 0 ]]; then
            echo "ARTIFACT_EXISTS=true" >> $GITHUB_ENV
          else
            echo "ARTIFACT_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Get artifact URL
        id: get_artifact_url
        run: |
          ARTIFACT_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=reports-${{ env.LATEST_COMMIT }}" | \
            jq -r '.artifacts[0].archive_download_url')
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV

      - name: Download artifact
        if: env.ARTIFACT_URL != 'null'
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "${{ env.ARTIFACT_URL }}" \
            -o artifact.zip
          unzip artifact.zip -d old

      # - name: Diff old and new
      #   id: diff
      #   if: env.ARTIFACT_URL != 'null'
      #   run: |
      #     DIFF_OUTPUT=$(diff -u hello.html old/hello.html || true)
      #     echo "DIFF_OUTPUT<<EOF" >> $GITHUB_ENV
      #     echo "$DIFF_OUTPUT" >> $GITHUB_ENV
      #     echo "EOF" >> $GITHUB_ENV

      - name: Zip all report.json files
        run: |
          zip -r reports.zip packages/*/report.json
        shell: bash

      - name: Upload New Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.sha }}
          path: reports.zip

      - name: Comment on PR with Artifact URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          script: |
            const artifactUrl = '${{ steps.upload-artifact.outputs.artifact-url }}';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Hello World artifact is available here: ${artifactUrl}`
            });

      # - name: Comment on PR with Diff Output
      #   if: github.event_name == 'pull_request'
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       const diffOutput = `${{ env.DIFF_OUTPUT }}`;
      #       github.rest.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: context.issue.number,
      #         body: `Diff output:\n\`\`\`\n${diffOutput}\n\`\`\``
      #       });
